apiVersion: apps/v1
kind: Deployment
metadata:
  name: nolan-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nolan-site
  template:
    metadata:
      labels:
        app: nolan-site
    spec:
      containers:
      - name: nolan-container
        image: nolan-app:v1
        imagePullPolicy: Never # Obligatoire pour Minikube
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/nolan_db"
---
apiVersion: v1
kind: Service
metadata:
  name: nolan-service
spec:
  type: NodePort
  selector:
    app: nolan-site
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001